version: '3.4'

services:
  bookmarkdb:
     image: mcr.microsoft.com/mssql/server

  bookmarkmanager.api:
    image: ${DOCKER_REGISTRY-}bookmarkmanagerapi
    build:
      context: .
      dockerfile: src/BookmarkManager.API/Dockerfile
