version: '3.4'

services:

  bookmarkdb:
    container_name: bookmarkdb
    environment:
      SA_PASSWORD: "SQLsaPass123"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1431:1433" 

  bookmarkmanager.api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings:DefaultConnection=Server=bookmarkdb;Database=BookmarkDb;User=sa;Password=SQLsaPass123;MultipleActiveResultSets=true"
    ports:
      - "8009:80"
    depends_on:
      - bookmarkdb
